apiVersion: v1
kind: Service
metadata:
  name: {{ include "mychart.fullname" . | lower }}-lb-service
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: http
spec:
  selector:
    {{- include "mychart.selectorLabels" . | nindent 6 }}
  ports:
    - protocol: TCP
      port: 80
      targetPort: {{ .Values.config.listenPort }}
  type: LoadBalancer
  externalTrafficPolicy: Local